theme: jekyll-theme-minimal
title: Google Foobar Solutions
description: These are the solutions to Google's Foobar challenges.
logo: /assets/Google%20Foobar%20sign-in%20error.jpg
favicon: /assets/google_foobar_sign_in_error_kQ0_icon.ico
show_downloads: true
